### ISSUE TITLE
why nim 0.19?

### ISSUE THREAD

**Issue by Compro-Prasad** [OrgTangle/ntangle#14]
Arch Linux hasn't yet shipped with 0.19.

**Comment by kaushalmodi** [comment]
I like living on bleeding edges (Emacs, Org mode, Hugo, and now Nim :)). I don't see much point for this tool to be backward compatible as it got developed using Nim devel version (now Nim 0.19.0).

What OS are you on? Try installing the latest Nim using https://github.com/dom96/choosenim#installation.

If your OS is a 64-bit GNU/Linux type, you can just download the static binary from Releases and run it.

Let me know if you face any issue.

**Comment by Compro-Prasad** [comment]
Fine then.

**Comment by kaushalmodi** [comment]
> Fine then.

So.. were you able to install Nim 0.19.0?

**Comment by Compro-Prasad** [comment]
Yes from the given link.
