### ISSUE TITLE
nim build fails on 0.6.3

### ISSUE THREAD

**Issue by 6AA4FD** [OrgTangle/ntangle#16]
[err.log](https://github.com/OrgTangle/ntangle/files/2758085/err.log)
I'm not a nim programmer, so I don't have any ideas here, but tell me if you can't reproduce and I'm welcome to provide more info.
nim: 0.19.0
nimble: 0.9.0

**Comment by kaushalmodi** [comment]
Hello, 

Thanks for the report. 

I believe that error is because I forgot to tag a release of ntangle after I updated a dependency last month. 

Can you verify if `nimble install ntangle@#head` works?

**Comment by kaushalmodi** [comment]
@6AA4FD Hello, this issue auto-closed as I associated it with a fix commit. But please let me know if the fix worked or not.

As you are not used to coding in nim, I'd suggest running `nimble install ntangle` instead of directly building using nim.

Alternatively, if you are using a GNU/Linux-type OS, you can download the statically built binary directly from https://github.com/OrgTangle/ntangle/releases/tag/v0.6.4.

**Comment by 6AA4FD** [comment]
nimble install ntangle@#head fails with: 
```
Downloading https://github.com/OrgTangle/ntangle using git
  Verifying dependencies for ntangle@#head
      Info: Dependency on cligen@>= 0.9.18 already satisfied
  Verifying dependencies for cligen@#head
 Installing ntangle@#head
   Building ntangle/ntangle using c backend
       Tip: 7 messages have been suppressed, use --verbose to show them.
     Error: nimble.nim(1106)         nimble
        ... nimble.nim(1044)         doAction
        ... nimble.nim(483)          install
        ... nimble.nim(359)          installFromDir
        ... nimble.nim(253)          buildFromDir
        ... nimble.nim(245)          buildFromDir
        ... Build failed for package: ntangle
        ... Details:
        ... nimble.nim(1106)         nimble
        ... nimble.nim(1044)         doAction
        ... nimble.nim(483)          install
        ... nimble.nim(359)          installFromDir
        ... nimble.nim(253)          buildFromDir
        ... nimble.nim(237)          buildFromDir
        ... tools.nim(37)            doCmd
        ... Execution failed with exit code 1
        ... Command: "/nix/store/ycxj05rshkj12bl2qpbjwd2v8g7lwcnj-nim-0.19.0/bin/nim" c --noBabelPath -d:release --path:"/home/quinn/.nimble/pkgs/cligen-#head"  -o:"/tmp/nimble_6289/githubcom_OrgTanglentangle_#head/ntangle" "/tmp/nimble_6289/githubcom_OrgTanglentangle_#head/src/ntangle.nim"
        ... Output: Hint: used config file '/nix/store/ycxj05rshkj12bl2qpbjwd2v8g7lwcnj-nim-0.19.0/config/nim.cfg' [Conf]
        ... Hint: system [Processing]
        ... Hint: ntangle [Processing]
        ... Hint: os [Processing]
        ... Hint: strutils [Processing]
        ... Hint: parseutils [Processing]
        ... Hint: math [Processing]
        ... Hint: bitops [Processing]
        ... Hint: algorithm [Processing]
        ... Hint: unicode [Processing]
        ... Hint: times [Processing]
        ... Hint: options [Processing]
        ... Hint: typetraits [Processing]
        ... Hint: strformat [Processing]
        ... Hint: macros [Processing]
        ... Hint: posix [Processing]
        ... Hint: ospaths [Processing]
        ... Hint: tables [Processing]
        ... Hint: hashes [Processing]
        ... Hint: terminal [Processing]
        ... Hint: colors [Processing]
        ... Hint: termios [Processing]
        ... Hint: sequtils [Processing]
        ... Hint: cligen [Processing]
        ... Hint: parseopt3 [Processing]
        ... Hint: argcvt [Processing]
        ... Hint: sets [Processing]
        ... Hint: textUt [Processing]
        ... ???(0, 0) Error: internal error: genLiteral: ty is nil
        ... Traceback from system (most recent call last)
```
nimble won't print an err log if the build of a release fails, it will just ask about trying head, though I could clone the release and try to build that if you'd like.

**Comment by kaushalmodi** [comment]
Let's try this:

```
nimble uninstall cligen
nimble install ntangle
```

Installing from head works for me, but let's see if the stable version install now works for you or not. 

The error log you posted the second time is different than the first one. For the first one, I understood the failure, but I'm trying to understand this second failure.

**Comment by 6AA4FD** [comment]
it worked, and now i feel super silly, though i assume nimble would handle that sort of thing for me. thank you for the help man!

**Comment by kaushalmodi** [comment]
> it worked

Btw, what worked? :)

The first snippet where you uninstall cligen, and install ntangle? Or the second snippet I pasted?

**Comment by 6AA4FD** [comment]
it was the uninstall cligen one, and i don't have a clue how frankly.
