### ISSUE TITLE
Support `begin_src` keys without values

### ISSUE THREAD

**Issue by Vindaar** [OrgTangle/ntangle#18]
I recently started to use `sagemath` via [ob-sagemath](https://github.com/sagemath/ob-sagemath) in some of my Org files. It needs to open a sage session in the background to run the code and requires the `:session` annotation for each block, for example:
```
Some text.
#+begin_src sage :session
φ = var('φ')
#+end_src
Some more text.
#+begin_src sage :session
print(φ)
#+end_src
where both of course run in the same session.
```
For `ntangle` the `:session` doesn't really matter of course. In the context I don't even care about actually tangling these into some file (be it a `.py` file or `.sage`).

The issue however is that this isn't allowed in `ntangle` at the moment. We raise an exception here:

https://github.com/OrgTangle/ntangle/blob/master/src/ntangle.nim#L407

I'm not sure whether there's a deeper reason that this isn't supported currently. I've written the following patch for myself locally:

```
diff --git a/src/ntangle.nim b/src/ntangle.nim
index 36a151b..158f83a 100644
--- a/src/ntangle.nim
+++ b/src/ntangle.nim
@@ -400,16 +400,20 @@ proc getHeaderArgs(file: string, line: string, lnum: int): LangAndArgs =
     if startHeaderArgs >= 2:
       headerArgsRaw = spaceSepParts[startHeaderArgs .. spaceSepParts.high]
   if haType != haNone:
-    #echo headerArgsRaw
+    var lastKey = false
     for i, h in headerArgsRaw:
       if h.len >= 2 and h[0] == ':':
-        if i == headerArgsRaw.high:
-          raise newException(OrgError, fmt("The header args are ending with a ':key' which is not valid. Found {headerArgsRaw}"))
+        if i == headerArgsRaw.high or lastKey:
+          headerArgPair = h[1 .. h.high] & " " & "<none>"
+          headerArgs.add headerArgPair
+          continue
         if headerArgPair != "":
           headerArgs.add(headerArgPair)
         headerArgPair = h[1 .. h.high]
         #echo fmt"{i} - {headerArgPair}"
+        lastKey = true
       else:
+        lastKey = false
         headerArgPair = headerArgPair & " " & h.strip(chars = {'"'})
         #echo fmt"{i} - {headerArgPair}"
         if i == headerArgsRaw.high:
```

As it's a bit hacky and I don't understand the ramifications in the broader context, I thought it's better to open an issue about it first.

**Comment by kaushalmodi** [comment]
Right now the expecting is that a :KEY header arg always has a VALUE. Related test: https://github.com/OrgTangle/ntangle/tree/master/tests/missing_arg_value

In haven't come across a use case like yours. But now that I do :)

That header arg parsing was mainly for parsing tangle related options and none of those are value-less. 

In ob-shell and others, the :session accepts a value for the session name so that you can have multiple sessions running in parallel. 

In this case, because a tangling related header arg :KEY will never be value-less, we can just throw away or ignore such key. But we'll need a test that parses these successfully:

```
#+begin_src sage :session :tangle yes
foo
#+end_src
```

```
#+begin_src sage :tangle yes :session
foo
#+end_src
```

```
#+begin_src sage :tangle yes :session :mkdirp yes
foo
#+end_src
```

**Comment by Vindaar** [comment]
Great hearing from you, @kaushalmodi!

> In ob-shell and others, the :session accepts a value for the session name so that you can have multiple sessions running in parallel.

Yup, works the same in `ob-sagemath`. If only a single one is needed, it's a bit annoying to give a name each time though.

> That header arg parsing was mainly for parsing tangle related options and none of those are value-less.

Ok, great. That was my intuition, but I wasn't certain that was actually the case. I'll try to make my patch a bit nicer & add the snippets you wrote as tests!
